---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 45.8.251.37
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa

vector:
  hosts:
    vector-01:
      ansible_host: 80.249.149.4
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa